version: "3"
services:
  reverseproxy:
    build:
      context: ./reverseproxy
    image: reverseproxy
  backend_user:
    build:
      context: ./backend-user
    image: udagram-api-user
  backend_feed:
    build:
      context: ./backend-feed
    image: udagram-api-feed
  frontend:
    build:
      context: ./udagram-frontend
    image: udagram-frontend:local 