apiVersion: v1
kind: Service
metadata:
  labels: 
    service: reverseproxy
  name: reverseproxy
spec:
  selector:
    sercive: reverseproxy
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080